### ISSUE TITLE
Mise à disposition des textes initiaux 

### ISSUE THREAD

**Issue by FMezard** [Chartes-TNAH/olivar-asselin#1]
Bonjour ! 

Il faudrait faire un dossier avec les textes des lettres au format HTML pour pouvoir commencer à les travailler.

**Comment by mggourio** [comment]
Bonjour Fanny,

D'accord, je m'en charge tout de suite !

**Comment by mggourio** [comment]
Je pense en fait qu'il vaut mieux prendre les textes bruts, car le format HTML ne va pas nous servir. Est-ce que cela vous convient donc si je mets les textes bruts sur le repository ?

**Comment by FMezard** [comment]
Ok, dans ce cas je pense que le plus simple serait de faire deux dossiers : 

- un dossier `correspondance` et un dossier `oeuvre_complete` . Dans le dossier `correspondance`, on pourra refaire un dossier `serie_01` et un dossier `serie_02` puis un fichier par lettres. 
- pour nommer les fichiers, le plus clair serait peut-être de faire `lettre_NN_AAAAMMJJ`.

Peux-tu t'occuper du dossier correspondance @HeathcoteA ?

Bon courage !

**Comment by HeathcoteA** [comment]
Coucou Fanny, 

Marie-Gaëlle s'occupe donc du dossier `correspondance` et je m'occupe de la création d'un dossier `oeuvre_complete`correspondant à l'oeuvre _Pourquoi on aime la France_ contenant deux fichiers avec ses discours. De la même manière, je vais adapter ce choix de dénomination en `discours_NN_AAAAMMJJ`.
:-)

**Comment by mggourio** [comment]
Salut,

Je vais mettre le corpus de lettres à disposition sur le repository.
Dans certaines lettres, il y a des dessins d'Olivar : j'ai laissé les adresses de ces images-là.
Par contre, dans chaque lettre se trouvent les reproductions des lettres : je n'ai pas laissé ces adresses-là.
Dites-moi ce que vous en pensez.

**Comment by FMezard** [comment]
Super, c'est parfait !
