### ISSUE TITLE
Encodage du TEI header 

### ISSUE THREAD

**Issue by FMezard** [Chartes-TNAH/olivar-asselin#10]
Il va falloir modifier le TEI header, notamment en ajoutant une balise `correspDesc`qui sera plus adaptée à notre édition de correspondance.

@architexte  pourriez-vous nous montrer les TEI header de l'école dont vous nous aviez parlé, que nous pourrions être amenés à utiliser.

Merci !

**Comment by algaudin** [comment]
Bonjour! 
Je me charge de modifier le tei Header du fichier XML, en ajoutant le correspdesc. Ensuite on pourra modifier la définition du relax ng.

**Comment by algaudin** [comment]
Ne me demandez pas pourquoi je l'ai réouverte, je ne le sais pas moi-même ^^
