### ISSUE TITLE
Suite du debbogage du RelaxNG

### ISSUE THREAD

**Issue by mggourio** [Chartes-TNAH/olivar-asselin#14]
Bonjour les archivistes !

Je poursuis le debbogage de notre RelaxNG. Grande nouvelle, il n'y a plus qu'une erreur !!
En effet, notre attribut xmlns de notre balise TEI n'est pas déclaré. Or le RelaxNG n'accepte pas qu'un attribut se nomme xmlns.

~~~xml
 <define name="TEI">
        <element name="TEI">
            <attribute name="xmlns"></attribute>
            <oneOrMore>
                <ref name="teiHeader"/>
                <ref name="text"/>
            </oneOrMore>
        </element>
    </define>
~~~
cela donne l'erreur `attribute must not be named "xmlns"`

A part ça, notre encodage est juste !

Avez-vous une idée pour résoudre cette erreur ?

**Comment by mggourio** [comment]
Bon, j'ai touvé la solution : il fallait déclarer xmlns comme un élément à la suite de TEI, et non comme un attribut.
Voici donc le code juste (ou presque juste car oxygen m'indique `missing children` au niveau de la balise fermante `define`)

~~~xml
 <define name="TEI">
        <element name="TEI" xmlns="http://www.tei-c.org/ns/1.0">
            <oneOrMore>
                <ref name="teiHeader"/>
                <ref name="text"/>
            </oneOrMore>
        </element>
    </define>
~~~
 Avez-vous une solution pour mon erreur de manque d'enfants ?

**Comment by FMezard** [comment]
J'ai cherché une partie de la soirée, j'ai essayé pas mal de trucs mais je n'ai rien trouvé ! 
Pour chercher la solution je me suis basé sur l'exemple laissé par Jean Baptiste Camps pour le projet `geste`.  Je vous mets le lien  [ici](https://github.com/Chartes-TNAH/geste/blob/master/src/Modele.rng) je pense que ça reste une bonne piste ! 
Bon courage
