### ISSUE TITLE
Structure des dossiers 

### ISSUE THREAD

**Issue by FMezard** [Chartes-TNAH/olivar-asselin#23]
Pour CapiTainiSer, il va falloir revoir notre structure de dossiers !

**Comment by mggourio** [comment]
Oui, il y a une hiérarchie bien particulière : 
1. dans un dossier olivar-asselin 
2. créer un dossier data
3. dans ce dossier data, mettre nos dossiers textgroup et notre schéma
4. dans chaque dossier textgroup il y a :
         a. le dossier textgroup
         b. le fichier __ cts __.xml du textgroup
5. dans chaque dossier textgroup se trouve :
         a. le fichier encodé
         b. le fichier __ cts__.xml de l'encodage

Et voilà !

**Comment by FMezard** [comment]
Parfait, comme ça je l'ai sous les yeux ! Je fais ça, je renommerai les fichiers dès qu'on aura décidé des identifiants.
