### ISSUE TITLE
Encodage TEI de la lettre_02_19170300

### ISSUE THREAD

**Issue by mggourio** [Chartes-TNAH/olivar-asselin#27]
Ave !

Je commence l'encodage en TEI de la lettre 2 de la première série de correspondance.

Encoderi te salutant ! ;)

**Comment by mggourio** [comment]
SOS !
Je n'arrive pas à lire ce qu'il y a sous certaines ratures. (mes cours de paléo commencent à dater !)
Selon vous, que faut-il que je mette dans le fichier encodé, à la place d'un mot que je n'arrive pas à déchiffrer ? Je mets des `XXX` ? :)

**Comment by PonteIneptique** [comment]
À toutes fins utiles : http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-unclear.html

**Comment by mggourio** [comment]
Bonjour,

Après des recherches à l'adresse donnée par M.Clérice, j'ai encodé comme ci-après les mots difficiles à déchiffrer :

~~~xml
<p> 
Je termine ma lettre, 
<unclear reason="illegible">forcé de me pencher</unclear>
 car je viens d’écrire longuement à Jean, et, dans la position où je suis, j’ai les fesses, les reins et le cou très <pb/>fatigués. Voici en effet comment je suis :
</p>
~~~

Je vais indiquer le changement dans l'issue sur les modifications du schéma.

**Comment by FMezard** [comment]
Désolée de m'en rendre compte maintenant, mais ta balise `figure` n'est pas juste en TEI ! Tu ne peux pas mettre `url` comme attribut de `figure`. Il faut faire 
```xml
<figure>
   <graphic url="URL"/>
</figure>
```

**Comment by mggourio** [comment]
D'accord, je vais modifier cela.
