### ISSUE TITLE
Encodage de la lettre_03_19170305

### ISSUE THREAD

**Issue by FMezard** [Chartes-TNAH/olivar-asselin#28]
Je m'y mets !

**Comment by FMezard** [comment]
Et voilà, les ennuis commencent ! J'ai un post-scriptum dans ma lettre qui arrive donc après le `<signed>`dans le `<closer>`, mais je ne suis pas autorisée à mettre de `<p>`à cet endroit là. Faut-il que je modifie le RelaxNG pour ajouter cette possibilité ou avez-vous une meilleure idée ?? 

Merci !

**Comment by mggourio** [comment]
Et peut-on mettre le post-scriptum en `note` ?

**Comment by mggourio** [comment]
As-tu remarqué que la transcription de wikisource n'est pas toujours juste ?
On est du coup obligé de lire l'image de la lettre manuscrite afin de placer correctement nos balises `del` (qui nous permettent d'encoder les ratures). 
Les festivités ne font que commencer ... !! ;)

**Comment by PonteIneptique** [comment]
Attention, `note` en TEI indique une note de l'éditeur

**Comment by algaudin** [comment]
En relisant les guidelines, j'ai découvert un élément `postscript`, complété des éléments `label` et `p`. Je vais le rappeler aussi dans l'issue #29 .

**Comment by FMezard** [comment]
Ok, merci beaucoup ! Je vais changer ça.
