### ISSUE TITLE
Amélioration du RelaxNG en parallèle de l'encodage des lettres

### ISSUE THREAD

**Issue by mggourio** [Chartes-TNAH/olivar-asselin#29]
Bonjour,

Au fur et à mesure de l'encodage des lettres, il va nous falloir modifier notre schéma afin d'y mettre des balises que nous n'avions pas prévu au départ.
Qu'en pensez-vous ?

Par exemple, @Keyuteotter a besoin d'une balise pour encoder un post-scriptum, et j'ai utilisé la balise `unclear` pour encoder une rature dont je ne suis pas sûre du déchiffrement. 

Comment voulez-vous que l'on procède ? On indique dans cette issue toutes nos balises fautives et ensuite on modifiera notre RelaxNG ensemble ?

**Comment by algaudin** [comment]
Effectivement, cela semble une bonne idée :)

De mon côté, en encodant la lettre 04 de la première série, je me suis servi de deux nouveaux éléments qui pourront (peut-être) vous être utile. N'hésitez pas à me dire si cela vous convient ou si vous pensez que d'autres balises peuvent convenir : 
- `gap` pour les ratures indéchiffrables
- `damage` pour tous les dommages subis par le texte. J'ai utilisé cette balise pour les passages indiqués comme censurés dans la transcription fournie par Wikisource, complété par un `type="censure"`

Dites-moi si cela vous semble pertinent, sinon je modifierai :)

**Comment by FMezard** [comment]
Ca me parait très bien, nous pouvons continuer à bien lister ici tous les éléments utilisés qui ne sont pas dans le relaxNG pour que celui-ci puisse être mis à jour quand nous aurons finis de rajouter des balises.

**Comment by mggourio** [comment]
Lors de l'encodage de la lettre 02, j'ai utilisé la balise `unclear` pour les passages difficilement lisibles, avec l'attribut `reason="illegible"`
 ~~~xml
<unclear reason="illegible">texte que j'ai déchiffré<unclear>
~~~
@algaudin tes balises sont très bien !

**Comment by algaudin** [comment]
Finalement, la balise `gap` parait surperflue, étant donné qu'on peut se servir de `del` comme une balise  vide.

**Comment by FMezard** [comment]
Penser à rajouter la balise `capture`dans la balise `figure`

```xml
<figure>
   <graphic url="URL"/>
</figure>
```

**Comment by mggourio** [comment]
J'ai trouvé l'erreur liée au `profilDesc` : il faut sortir la balise du `fileDesc` et c'est tout ! Il faudra penser à modifier notre RelaxNG et les lettres encodées déjà pushées en conséquence.

Bon courage pour la suite de nos encodages !

**Comment by FMezard** [comment]
J'ai utilisé un `figDesc` dans une lettre pour mettre la légende de dessins présents dans les lettres. Est-ce que cela vous convient ?

**Comment by FMezard** [comment]
Deuxième question : est-ce que vous pensez qu'il serait possible de mettre 2 `closer` ? (c'est dans la lettre 12 ( #51 ), je ne vous pas comment faire autrement.

**Comment by algaudin** [comment]
Aucun souci, je crois que la DTD nous le permet par les `one-or-more` ?

**Comment by mggourio** [comment]
Je me rallie au `figDesc` !
Pour les 2 `closer`, je suis de l'avis de @algaudin : tout est possible avec RelaxNG !!

**Comment by FMezard** [comment]
Du coup ça donne ça ! Ca fait une structure un peu complexe, mais je ne vois pas trop comment simplifier. 
```xml
<closer>
                    <salute>Je t’embrasse, et je t’envoie une xxxxxxx chaude léchade du bon chien
                        Marion. </salute>
                    <signed><hi rend="underline"><persName corresp="#oasselin"
                        >Papa</persName></hi></signed>
                </closer>
                <postscript>
                    <label>P.S.</label>
                    <p>Je souffre beaucoup de ne savoir pas dessiner : ne manques pas d’occasions
                        d’étudier le dessin. Ton oncle Jules et ta tante Éliza te donneront des
                        leçons – c’est tout</p>
                </postscript>

                <figure>
                    <graphic
                        url="https://upload.wikimedia.org/wikipedia/commons/1/12/Chien_assis.png"/>
                    <figDesc>Fin de l’histoire du bon chien <hi rend="underline">Marion</hi></figDesc>
                </figure>

                <closer><placeName>Witley-Camp, en Angleterre,</placeName><date>10
                    janvier</date></closer>
                <figure>
                    <graphic
                        url="https://fr.wikisource.org/wiki/Correspondance_-_Lettre_du_10_janvier_1918_(Asselin)#/media/File:Chien_fait_la_belle.png"/>
                    <figDesc>Portrait fidèle du bon chien Marion recevant sa ration de friandises.
                        On les lui met sur le bout du nez, il les fait sauter en l’air et il les
                        attrape au vol. Mais pour remuer, il attend le commandement. Ce portrait a
                        été fait par un officier du 10e pour M. Pierre Asselin, écolier,
                        élève-canonnier. Papa. </figDesc>
                </figure>
```

**Comment by mggourio** [comment]
Parfait !

**Comment by algaudin** [comment]
C'est top !

**Comment by mggourio** [comment]
Bonjour, 

Je suis en train de relire les lettres. Et au regard des originaux, il est plus logique de sortir le `salute` de l'`opener` de cette manière :
~~~xml
<opener rend="right">
<date when="1917-03-05">Lundi, 5/3/17</date>
</opener>
<space dim="vertical" quantity="1" unit="lines"/>
<salute>Ma bien chère femme,</salute>
~~~
Est-ce que cela vous convient ?
Si oui, il faudra modifier le schéma en conséquence !

Bon courage pour la suite !

**Comment by FMezard** [comment]
Ca me va très bien! Juste deux petites remarques : 
- il ne sert à rien de numéroter les `<p>`à la main, je viens de finir le script qui permet de le faire automatiquement. 
- il est peut être plus pratique d'attendre d'avoir les fichiers vraiment liés au relaxNG avant de faire toutes les relecture, histoire de ne pas multiplier le travail.

**Comment by algaudin** [comment]
En relisant les guidelines pour le Relax NG, j'ai vu qu'il fallait explicitement spécifier par `<empty/>` quand un élément était vide (ce qui est le cas pour `<unclear> <del> <space> <pb>` et `<graphic>`)

**Comment by FMezard** [comment]
Il faudrait également rajouter le `refsDecl`  dans un `encodingDesc` et l'attribut `n` dans le `p`. 

Voilà l'exemple pour le `refsDecl` : 

```xml
<refsDecl n="CTS">
  <cRefPattern 
      n="level3"
      matchPattern="(\w+).(\w+).(\w+)"
      replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1']/tei:div[@n='$2']/tei:div[@n='$3'])">
      <p>This pointer pattern extracts level1 and level2 and level3</p>
  </cRefPattern>
```

**Comment by algaudin** [comment]
Je me charge d'ajouter tous ça et de modifier le schéma comme il convient :)
