### ISSUE TITLE
Exemple d'encodage préalable au schéma RelaxNG - correspondance

### ISSUE THREAD

**Issue by FMezard** [Chartes-TNAH/olivar-asselin#4]
Rebonjour, 

Pour pouvoir encoder les textes, il va falloir mettre en place un schema RelaxNG pour avoir un encodage en TEI homogène pour toutes les lettres de la correspondance. Il faudra au préalable réfléchir aux balises utiles.

**Comment by algaudin** [comment]
Salut!

Je vais m'en charger. 
Voici la procédure que je vous propose. Je prendrai la première lettre de la correspondance, faire un encodage en TEI all. Je mettrai le texte encodé sur une deuxième branche, pour qu'on soit bien d'accord sur les balises les plus utiles. On verra après pour le RelaxNG. 

Cela vous convient-il ?

**Comment by mggourio** [comment]
👍

**Comment by algaudin** [comment]
Bonjour à tous!

Vous pourrez trouver sur la branche "issue-4", dans le dossier "Schéma", un exemple d'une lettre encodée en TEI. J'ai essayé de ne mettre uniquement que les balises les plus utiles. J'ai aussi ajouté quelques commentaires concernant des balises qui ne sont pas utilisées dans cet exemple, mais qui pourraient être utiles pour d'autres textes. J'ai aussi mis des balises pour un éventuel index des noms de personnes (à voir si cela est vraiment utile selon la procédure que l'on va suivre). 

N'hésitez pas à me dire si vous trouvez des balises qui vous semblent importantes et que j'aurais oublié. 
En attendant la validation des balises, je vais me renseigner sur le fonctionnement du RelaxNG. 

Bon samedi.

**Comment by FMezard** [comment]
Salut Alexandre, 

C'est super ce que tu as fait !! Par contre, wikipedia ne respecte pas les retours à la ligne, je ne pense pas que ça vaille le coup de mettre tous les `<lb>`, on va perdre beaucoup de temps. 

Pour le reste, il n'y a plus qu'à faire le relaxNG ! 

Bonne semaine, 

Fanny

**Comment by HeathcoteA** [comment]
Coucou ! 
Suite à l'encodage d'Alexandre, j'ai trouvé les informations de conservation de la correspondance à cette adresse : [https://archivesdemontreal.ica-atom.org/olivar-asselin-1912-1933] et l'instrument de recherche associé : [https://archivesdemontreal.ica-atom.org/downloads/fonds-jean-asselin-189-1996.pdf](url) 
:-)

**Comment by FMezard** [comment]
Super, je ferme l'issue !
