### ISSUE TITLE
Liaison du relaxNG avec les lettres encodées

### ISSUE THREAD

**Issue by FMezard** [Chartes-TNAH/olivar-asselin#53]
@architexte 

Nous avions réussi à lier nos lettres encodées en TEI à notre schéma relaxNG, cependant, depuis que nous avons changé la structure de nos dossiers, nous n'arrivons plus à recréer cette liaison. Cela nous bloque pour mettre à jour le relaxNG au vu des nouveaux éléments rencontrés dans l'encodage des lettres

Nous avons également un problème avec notre élément racine, car nous n'arrivons pas à déclarer l'`xmlns`dans le relaxNG. 

Merci

**Comment by algaudin** [comment]
J'ai testé en modifiant le chemin vers le RelaxNG (en modifiant de `../data/correspondance.rng` à `../../correspondance.rng`) et j'ai enlevé le `xmlns` de la balise `TEI`. Le document XML semble être lié à la RelaxNG. Certaines balises sont alors soulignées. Par exemple, la balise `salute` est mal placée, parce que cela ne correspond pas au RelaxNG.

Mais il nous reste toujours ce problème du `xmlns`.

**Comment by algaudin** [comment]
Il faudra surement changer le chemin vers le schéma RelaxNG, parce qu'on a pas encore crée un sous-dossier par lettre, accompagné du fichier `__cts__.xml`.

**Comment by algaudin** [comment]
Bonjour à tous, 

Je me suis penché sur le problème du xmlns. Oxygen nous affichait 

> element "TEI" not allowed anywhere; expected element "TEI" (with xmlns="").

Dans le fichier `correspondance.rng`, j'ai ajouté dans la balise `<element name="TEI">`  l'attribut `xmlns="http://www.tei-c.org/ns/1.0"`. Maintenant, il nous indique 

> missing children

Pourtant, en relisant l'intégralité du fichier de notre relaxNG, je n'ai pas trouvé comment résoudre cette erreur. 
Je ne sais pas si on est sur la bonne voie, mais peut-être que suite à cela,  l'un de vous pourra trouver la solution à cette énigme :)

**Comment by algaudin** [comment]
Je crois que j'ai réussi (enfin) à relier le schéma et nos textes en TEI. 
Dans le fichier `correspondance.rng`, j'ai ajouté dans `<grammar>`  `xmlns:ns="http://www.tei-c.org/ns/1.0"`, et j'ai fait de même dans le fichier TEI, dans la balise `<TEI>`.
Par magie, cela a fonctionné ...

Du coup, je vais modifier le schéma, selon les commentaires faits dans l'issue 29.
Cela vous va ?

**Comment by FMezard** [comment]
C'est bon, le schéma est bien relié, merci @algaudin :)
