### ISSUE TITLE
Structuration des métadonnées des lettres : essai avec la lettre wikid1.wikid01

### ISSUE THREAD

**Issue by mggourio** [Chartes-TNAH/olivar-asselin#55]
Il va falloir structurer les métadonnées des lettres en associant un fichier `__cts__` à chaque lettre et à chaque groupe de lettres.

Commençons par la lettre `wikid1.wikid01`, afin d'avoir ensuite un exemple pour les lettres suivantes !

**Comment by algaudin** [comment]
Bonjour, 

J'ai essayé de créer le dossier `__cts__.xml` pour le niveau "version", à savoir la lettre. J'ai un doute sur les éléments à utiliser ou non. Est-ce bien comme cela @PonteIneptique ?
~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<ti:version urn="urn:cts:wikisource:wikidQ3350623.wikid1.wikid01"
    xmlns:cpt="http://purl.org/capitains/ns/1.0#"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:ti="http://chs.harvard.edu/xmlns/cts"
    workUrn="urn:cts:wikisource:wikidQ3350623.wikid1" xml:lang="fre"
    groupUrn="urn:cts:wikisource:wikidQ3350623">
    <ti:title xml:lang="fre">Lettre du 26 Novembre 1916</ti:title>
        <ti:label xml:lang="fre">Lettre du 26 Novembre 1916</ti:label>
        <ti:description xml:lang="fre">Lettre écrite par Olivar Asselin.</ti:description>
        <cpt:structured-metadata>
            <dc:creator xml:lang="fre">Olivar Asselin</dc:creator>
            <dc:title xml:lang="fre">Lettre du 26 Novembre 1916</dc:title>
            <dc:subject xml:lang="fre">Lettre écrite par Olivar Asselin.</dc:subject>
            <dc:publisher xml:lang="fre">Wikisource</dc:publisher>
            <dc:date>1916-11-26</dc:date>
            <dc:type>text</dc:type>
            <dc:language>fre</dc:language>
        </cpt:structured-metadata>
</ti:version>
~~~

**Comment by PonteIneptique** [comment]
Cela me semble correct au niveau des `structured-metadata`. Sur le reste par contre : 

Les dossiers contiennent des works (soit une lettre ou un ensemble de lettre suivant vos choix). Le fichier `__cts__.xml` des dossiers works doivent comprendre à la fois une description du `work` et des `editions` : http://capitains.org/pages/guidelines.html#work-metadata-file

**Comment by mggourio** [comment]
Bonjour, 

J'ai mis en place un fichier `__cts__.xml` pour le niveau work (=la série).
~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<ti:work xmlns:ti="http://chs.harvard.edu/xmlns/cts"
    groupUrn="urn:cts:wikisource:wikidQ3350623"
    urn="urn:cts:wikisource:wikidQ3350623.wikid1"
    xml:lang="fre">
    <ti:title xml:lang="fre">Correspondance</ti:title>
    <ti:edition 
        workUrn="urn:cts:wikisource:wikidQ3350623.wikid1">
        <ti:label xml:lang="fre">Série 1</ti:label>
        <ti:description xml:lang="fre">
            Série de treize lettres de guerre écrites par Olivar Asselin entre 
le 26 novembre 1916 et le 4 juin 1918
        </ti:description>
    </ti:edition>
</ti:work>
~~~

@PonteIneptique, est-ce correct ?

**Comment by PonteIneptique** [comment]
@mggourio Non mais on avance.

Le work correspond en CTS à l'idée de l'oeuvre, tandis que l'édition correspond à sa réalisation. Par exemple: 
- `work` = Les Mains Sales de Sartre, 
- `edition` = Les Mains Sales édité chez Gallimard converti en XML à l'ENC

Pour le moment, vous avez découpé vos oeuvres 1 lettre = 1 fichier, ce qui veut dire pour le moment 1 lettre (work) = 1 transcription (edition, le fichier xml). 

Est-ce que cela vous met sur la voie ?

**Comment by mggourio** [comment]
Nous pensions que la version était la lettre encodée, que le work était une série de lettres et que le textgroup était l'ensemble des oeuvres encodées d'Olivar Asselin.
Mais je ne suis pas sûre d'avoir compris. Car si ce n'est pas ça, comment puis-je décrire les métadonnées de la série ? Est-ce mieux ainsi (j'ai modifié le `ti:label`)?
~~~xml
<ti:work xmlns:ti="http://chs.harvard.edu/xmlns/cts"
    groupUrn="urn:cts:wikisource:wikidQ3350623"
    urn="urn:cts:wikisource:wikidQ3350623.wikid1"
    xml:lang="fre">
    <ti:title xml:lang="fre">Correspondance</ti:title>
    <ti:edition 
        workUrn="urn:cts:wikisource:wikidQ3350623.wikid1">
        <ti:label xml:lang="fre">Correspondance d'Olivar Asselin éditée par Wikisource 
et convertie en XML par l'ENC</ti:label>
        <ti:description xml:lang="fre">
            Série de treize lettres de guerre écrites par Olivar Asselin entre 
le 26 novembre 1916 et le 4 juin 1918
        </ti:description>
    </ti:edition>
</ti:work>
~~~

Et les métadonnées pour le niveau textgroup (=Olivar Asselin) sont-elles correctes ?
~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<ti:textgroup xmlns:ti="http://chs.harvard.edu/xmlns/cts" 
urn="urn:cts:wikisource:wikidQ3350623">
    <ti:groupname xml:lang="fre">Olivar Asselin</ti:groupname>
</ti:textgroup>
~~~

Merci @PonteIneptique

**Comment by PonteIneptique** [comment]
Nous pourrons en rediscuter mardi (pensez à venir m'en parler).
Il va falloir soit faire un dossier par lettre, soit regrouper vos lettres dans un fichier pour être compatible avec CapiTainS.

**Comment by mggourio** [comment]
Oui, nous avons prévu de faire un dossier par lettre (la lettre étant de niveau version).
Nous viendrons vous voir mardi après le cours.
Bon week-end monsieur.

**Comment by PonteIneptique** [comment]
Merci et à vous aussi

**Comment by algaudin** [comment]
Après les discussions que nous avons eues hier concernant le niveau correspondant au work, j'ai modifié le contenu du fichier __cts__.xml : 
~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<ti:work urn="urn:cts:wikisource:wikidQ3350623.wikid1"
   xmlns:cpt="http://purl.org/capitains/ns/1.0#"
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:ti="http://chs.harvard.edu/xmlns/cts"
   xml:lang="fre"
   groupUrn="urn:cts:wikisource:wikidQ3350623">
   <ti:title xml:lang="fre">Série 1 de la correspondance de guerre d'Olivar Asselin</ti:title>
   <ti:label xml:lang="fre">Série 1 de la correspondance de guerre d'Olivar Asselin</ti:label>
   <ti:description xml:lang="fre">Ensemble de lettres écrites par Olivar Asselin lors de la Première Guerre Mondiale.</ti:description>
   <cpt:structured-metadata>
      <dc:creator xml:lang="fre">Olivar Asselin</dc:creator>
      <dc:title xml:lang="fre">Série 1 de la correspondance de guerre d'Olivar Asselin</dc:title>
      <dc:subject xml:lang="fre">Ensemble de lettres écrites par Olivar Asselin lors de la Première Guerre Mondiale.</dc:subject>
      <dc:publisher xml:lang="fre">Wikisource</dc:publisher>
      <dc:date>1916-11-26/1918-06-04</dc:date>
      <dc:type>text</dc:type>
      <dc:language>fre</dc:language>
   </cpt:structured-metadata>
   <ti:edition 
      workUrn="urn:cts:wikisource:wikidQ3350623.wikid1" 
      urn="urn:cts:wikisource:wikidQ3350623.wikid1.wikid01">
      <ti:label xml:lang="fre">Série I de la correspondance de guerre d'Olivar Asselin éditée par Wikisource 
         et convertie en XML par l'ENC</ti:label>
      <ti:description xml:lang="fre">
         Encodage XML-TEI de la première série de treize lettres de guerre écrites par Olivar Asselin entre 
         le 26 novembre 1916 et le 4 juin 1918
      </ti:description>
   </ti:edition>
</ti:work>
~~~

@PonteIneptique Est-ce correct ainsi  ?

**Comment by mggourio** [comment]
Et voici le fichier `__cts__.xml` pour le niveau textgroup
~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<ti:textgroup xmlns:ti="http://chs.harvard.edu/xmlns/cts" urn="urn:cts:wikisource:wikidQ3350623">
    <ti:groupname xml:lang="fre">Olivar Asselin</ti:groupname>
</ti:textgroup>
~~~
@PonteIneptique est-ce que cela est correct ?

**Comment by algaudin** [comment]
En testant sur [](https://capitains-validator.herokuapp.com/) le semblant de fichier cts que l'on a crée, on obtient le résultat suivant : 
![capture du 2018-02-16 11-55-19](https://user-images.githubusercontent.com/33345655/36304610-867733f8-1310-11e8-8b88-72bce0b1773d.png)

**Comment by PonteIneptique** [comment]
La seule erreur visible : `ti:label` et `ti:description` ne font pas sens comme enfant de `ti:work`
