### ISSUE TITLE
Encodage  de l'oeuvre complète en TEI

### ISSUE THREAD

**Issue by FMezard** [Chartes-TNAH/olivar-asselin#7]
Coucou !

On reste avec le schema TEI-all pour l'oeuvre complète, on peut donc déjà commencer à l'encoder !

**Comment by HeathcoteA** [comment]
Coucou ! 
Je me suis occupée de la TEI aujourd'hui, je vais essayer de vous l'envoyer :-) 

J'ai une dernière petite question concernant l'encodage des noms de lieux dans le texte des discours, faut-il les encoder justement ? 

Bonne soirée !

**Comment by HeathcoteA** [comment]
Avis à la team, 
J'ai visiblement fais une erreur de git-age... Les fichiers texte brut sont encodés mais en voulant vous transmettre le fichier TEI j'ai fais disparaitre ces fameux fichiers ! Je vous envoie un SOS mais l'erreur est rattrapable (j'irai rechercher les beaux fichiers textes). Je vais relire le cours pour vous envoyer correctement la TEI demain !

**Comment by FMezard** [comment]
Je n'ai pas très bien compris ton problème : est-ce que tu as fait un push sur le repository  ? Je ne vois pas de nouvelle branche pour le moment

On prendra un moment pour voir ça ensemble demain en tout cas, pas de soucis et merci pour l'encodage ! :)
