### ISSUE TITLE
Reorganisation totale des fichiers / dossiers pour être fidèle à CapiTainS

### ISSUE THREAD

**Issue by FMezard** [Chartes-TNAH/olivar-asselin#72]
Il semblerait qu'il faille changer très franchement notre façon d'encoder / organiser les dossiers pour CapiTainS : 

Après la relecture et la numérotation des lettres, il va finalement falloir recréer un grand dossier TEI par série de lettres vu que sinon ça ne respecte pas la capitainisation. On va donc avoir : 

DATA/
 
  - asselin(wikidQ...)/
       - `__cts__.xml`
       - wikid01
          - `__cts__.xml`
          - wiki01.wikid1
       - wikid02
           - ` __cts__.xml`
           - wikid02.wikid1
       - wikid03
           - `__cts__.xml`
          - wikid03.wikid1

L'autre possibilité est de supprimer le niveau série et de ne garder que les fichier lettres, avec du coup un fichier __cts__ par lettre. Le soucis est que ça ne nous laisserait plus qu'un niveau de citation et que ce serait moins élégant.

**Comment by mggourio** [comment]
Et bien je préfèrerai la seconde possibilité car cela nous éviterait de modifier notre schéma et de chambouler nos encodages TEI.

**Comment by FMezard** [comment]
Oui, c'est vrai que c'est pas très pratique, mais pour le `refsDecl`, ça nous permettra d'avoir deux niveaux de citation : la lettre et le paragraphe, ce qui serait à mon sens plus logique.

**Comment by HeathcoteA** [comment]
Personnellement je suis pour garder la classification en séries qui respecterait la capitainisation et le `refsDecl`

**Comment by mggourio** [comment]
D'accord, mais avec la seconde solution, on a aussi 2 niveaux de citations : lettre et paragraphe, non ?

**Comment by algaudin** [comment]
Je suis plutôt d'accord avec Amandine et Fanny.
Avec la seconde solution, si j'ai bien compris, le niveau lettre serait superflu ?

**Comment by mggourio** [comment]
Avec la solution 2, nos lettres encodées remontent au niveau `work` et la citation serait par exemple `wikid14.wikid1` où `wikid14` est le dossier comprenant la lettre, et `wikid1` est l'édition de la lettre accompagnée de son `__cts__`

**Comment by FMezard** [comment]
Je parlais du `refsDecl` et du `replacementPattern` !

**Comment by algaudin** [comment]
Honnêtement, il me semble plus facile de modifier ne serait-ce que légèrement le relaxng (il y a "que" le correspAction à transformer en front, ainsi que l'élément front), plutôt que de faire de multiples cts :)

**Comment by mggourio** [comment]
Bon d'accord. Mais je maintiens quand même que la solution 2 est ce qui nous permet de modifier le moins de choses, surtout ce relaxNG sur lequel on a déjà beaucoup, mais alors beaucoup, travaillé !!

**Comment by mggourio** [comment]
Bon allez, soyons fous, c'est parti pour la solution 1 ! La maison ne recule devant aucun sacrifice !!
