### ISSUE TITLE
Définition du modèle d'encodage de la correspondance

### ISSUE THREAD

**Issue by algaudin** [Chartes-TNAH/olivar-asselin#8]
Bonjour à tous, 

Suite aux remarques de M. Jolivet,  il faudrait revoir le modèle d'encodage de la correspondance. 

Est-ce que vous souhaitez que l'on conserve l'encodage actuellement effectué, auquel cas il faudrait ajouter un <correspDesc> ou préférez-vous que l'on fonctionne sur le modèle d'un TEICorpus avec un TEI Header propre à l'édition encodée, puis un TEI par lettre, avec son propre TEI Header suivi du texte (dans ce cas, il faudra revoir le schéma en Relax NG) ?

Bonne soirée :)

**Comment by FMezard** [comment]
Après réflexion, je me suis dit que c'est peut être le plus simple de faire un fichier par lettre. Cela nous simplifiera la tâche pour la capitainisation (en faisant du coup un fichier cts par lettre). Ca sera aussi plus simple pour gérer le travail en équipe : chacun peut encoder sa lettre dans un fichier indépendant. Après, ça pose le problème de la répétition du TEIheader dans chacun des fichiers. 

Qu'en pensez-vous ?

**Comment by algaudin** [comment]
Je suis d'accord avec toi. Il me semble plus facile de faire un fichier par lettre que de gérer et travailler à plusieurs sur un fichier TEI Corpus, quitte à répéter le TEI header.

**Comment by mggourio** [comment]
La solution d'un fichier XML par lettre me en effet semble la plus simple, tant pour le partage de l'encodage que pour la capitanisation, et tant pis pour la répétition du teiHeader. A moins qu'il soit possible de faire un fichier TEI juste pour le teiHeader, et de relier nos fichiers de lettres à ce fichier ?

**Comment by FMezard** [comment]
Du coup si personne ne s'y oppose, on reste sur ce choix. Je vais retirer le `group` de notre modèle d'encodage TEI, puisque nous n'avais plus de groupe de texte, mais un seul texte par fichier.
