### ISSUE TITLE
Résoudre les problèmes de tests avec Travis

### ISSUE THREAD

**Issue by algaudin** [Chartes-TNAH/olivar-asselin#87]
Comme vous le savez, Travis nous fait la guerre depuis le début de notre projet. Nous avons perdu la bataille, certes, mais pas la guerre ! 

Dans notre défense, il semblait y avoir plusieurs problèmes, qui nous ont été révélés par notre espion dans le camp ennemi, notre cher CapiTainS Guideline Single File Validator : 

- URN Informations

- Correct xml:lang attribute

- Passage level parsing

- Correct xml:lang attribute 

- RefsDecl parsing

- Passage level parsing

- Unique nodes found by XPath

- Duplicate passages

- Forbidden characters

Je suis persuadé qu'on arrivera à faire une trêve, dès qu'on aura résolu tous ces problèmes. 
Des idées  ?

**Comment by mggourio** [comment]
En relisant les guidelines CapiTainS, j'ai vu qu'il faut ajouter un `tei:` pour chaque élément du chemin XPath qu'il y a dans le `refDecl`.

Est-ce que cela favorise une trêve ?

**Comment by HeathcoteA** [comment]
Je pense que dans la toute première balise `text`, il faut ajouter les attributs `xml:lang="fr"` et `xml:base="urn_de_l_edition"` . Il faudra sûrement modifier le relax ng une fois de plus.

**Comment by algaudin** [comment]
Je vais modifier tout ça, et tester avec le validateur Capitains, avant de faire tourner cela sur Travis. 
Merci :)

**Comment by algaudin** [comment]
J'ai modifié tout ce que vous m'aviez dit et voici le résultat des tests : 

Ceci est le résultat pour wikid1 : 
![test_wikid1](https://user-images.githubusercontent.com/33345655/36490011-9d92b8e4-1727-11e8-9a84-56cb5601a5c0.png)

Pour wikid2 : 
![test_wikid2](https://user-images.githubusercontent.com/33345655/36490019-a101fddc-1727-11e8-93b4-2e652d56dd5d.png)

Et pour le wikid3 : 
![test_wikid3](https://user-images.githubusercontent.com/33345655/36490022-a2ebd32a-1727-11e8-9f09-89ee9c25818f.png)


Pensez-vous que je peux tout pusher ?

**Comment by FMezard** [comment]
OUI !!! :D

**Comment by algaudin** [comment]
J'ai fait une pull request, mais il apparait toujours un problème : 

- Available in Inventory

Et il y a en plus un problème sur le schéma `Text not allowed here`, lignes 781 et 993 du fichier xml wikid1

En tout cas, on est sur le chemin de la victoire ! :)

**Comment by FMezard** [comment]
@PonteIneptique 

Nous y sommes presque, mais nous n'arrivons pas à régler le problème de "Available in Inventory" après vérification attentive des urn dans les fichiers cts. 

Nous avons aussi un problème de DTD sur la première série de lettre que nous n'arrivons pas à identifier. 

Merci !

**Comment by PonteIneptique** [comment]
Votre URN est fausse : URN !+ Nom de fichier avec extension :)

**Comment by algaudin** [comment]
Merci! 

Après de nouveaux tests, il y a toujours le problème de DTD sur le fichier correspondant à la première série de lettres. J'ai pourtant modifié à plusieurs reprises le fichier relaxng, sans succès. Des idées ?

**Comment by PonteIneptique** [comment]
Votre schéma n'est malheureusement pas pris en compte par Hooktest qui ne teste que le schéma TEI général. Il est donc probable que votre schéma ne soit pas compatible TEI sur ces deux points. Pouvez-vous m'indiquer les lignes correspondantes ?

**Comment by algaudin** [comment]
Finalement, grâce à tout le monde, on a trouvé notre erreur. Notre schéma nous permettait d'ajouter du texte directement dans une balise `<div>`, mais la TEI ne l'autorise pas. Nous avons donc ajouté les balises `<p>` manquantes.
