### ISSUE TITLE
Identifiants des lettres

### ISSUE THREAD

**Issue by mggourio** [Chartes-TNAH/olivar-asselin#9]
Bonjour,

Que pensez-vous de définir les identifiants des lettres en même temps qu'on les encode ?
Si oui, il faut songer à des identifiants pertinents et qui nous permettent de nous y retrouver dans la correspondance.

**Comment by HeathcoteA** [comment]
Coucou, 
j'ai retrouvé une liste de sources d'identifiants dans mon cours, il faut qu'on regarde VIAF, RAMEAU, IDREF ou WIKIDATA.

**Comment by algaudin** [comment]
Très bien, merci ! 
Juste une petite confirmation : il nous faut bien trouver un identifiant pour le niveau "textgroup", c'est-à-dire l'auteur, un pour le niveau "work" correspondant à chacune des séries (et pour les discours), et un pour un niveau correspondant à la lettre ?

**Comment by mggourio** [comment]
Salut !
Oui, c'est bien ça, il nous faut un identifiant pour l'auteur, un par groupe de textes et un dernier par lettre.

**Comment by HeathcoteA** [comment]
Sur wikidata, Olivar Asselin est identifié par `Q3350623` , la notice d'autorité BNF lui attribut `12917641` et sur VIAF c'est le `23039705`.

**Comment by FMezard** [comment]
Je pense qu'on pourrait rester sur wikidata, vu que notre source est elle-même issue de wikisource.

**Comment by mggourio** [comment]
Bonne idée !

**Comment by HeathcoteA** [comment]
Conformément au modèle `urn:cts:greekLit:tlg0012.tlg001`, peut-on envisager d'identifier la première lettre par `urn:cts:freCor:wikidQ3350623.wikid001` ? En suivant `greekLit`devient `freLit` pour le français et on peut créer `freCor` puisque nous avons de la correspondance française ? 
`Q3350623` étant l'identifiant wikidata d'Olivar Asselin devient `wikidQ3350623` et enfin, création de l'identifiant de la première lettre `wikid001` ?

**Comment by algaudin** [comment]
L'idée du `freCor` pour le namespace est une excellente idée ! 
Par contre, j'ai un doute concernant `wikid001`. Est-ce le niveau de l'identifiant pour la première lettre ou la première série de lettres ?

**Comment by mggourio** [comment]
Oui, `wiki001` est l'identifiant de la première lettre. Et donc `wiki002` est celui de la deuxième lettre. Tandis que `wiki0001`est l'identifiant de la première série.

**Comment by HeathcoteA** [comment]
SOS ! Je viens de penser que nous n'avons pas que de la correspondance !!! Les deux discours de l'oeuvre complète Pourquoi on aime la France ne peuvent pas être identifiés par freCor... Doit-on faire un freCor et un freDisc ? Ou simplement oublier cette distinction et trouver un namespace commun aux deux genres ?

**Comment by mggourio** [comment]
Je pense que le plus simple est d'utiliser un namespace commun pour nos lettres et nos discours. On peut reprendre le `freLit` ou bien en inventer un autre, plus personnalisé.
Q'en pensez-vous ?

**Comment by algaudin** [comment]
Ah oui ! 
On peut éventuellement reprendre `freLit`, ça semble assez général pour contenir les deux ? Ou on peut prendre totalement autre chose aussi.

**Comment by FMezard** [comment]
Sinon, comme on a un corpus déjà constitué, on peut peut-être prendre `oaLit` (pour Olivar Asselin, parce que `assLit` ça sonne pas terrible :P ).

**Comment by mggourio** [comment]
oaLit est une bonne idée, et comme ça on a personnalisé notre namespace !

**Comment by FMezard** [comment]
Du coup, si on résume, ça donne : `urn:cts:oaLit:wikidQ3350623.wikid1.wikid01`  pour la première lettre. Je me suis permise d'enlever quelques zéros, vu qu'on ne va probablement pas encoder plus de 99 lettres ! 

@PonteIneptique Est-ce que cet identifiant vous parait satisfaisant ?

**Comment by PonteIneptique** [comment]
Cela me semble pas mal, mais pourquoi pas urn:cts:wikisource: pour le namespace ?

**Comment by FMezard** [comment]
Oui d'accord, nous allons le modifier.
